### ISSUE TITLE
Gist line numbers and lines do not align correctly

### ISSUE THREAD

**Issue by jberger** [blogs-perl-org/blogs.perl.org#184]
I have a css request which I believe I have tuned to not hurt anything else. Embedded gists lines and line numbers do not line up correctly. I believe its due to the hard-coded `pre` styling that came from #120. 

If this line is added to the css it should fix it (note that I don't care what height you choose).

``` css
.gist .line, .gist .linenumber {
    line-height: 1.5em;
}
```

Thanks!
